### ISSUE TITLE
Quick start guide doesn't specify which operating systems are supported by reaction-development-platform

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/docs#1]
Some people are trying to follow the quick start guide on Windows (outside of WSL), leading them to errors when running the `make` command.

We should add a note to list the supported operating systems. If Windows isn't officially supported, we should make it clear at the top of the page. Even better though, we could include a section explaining how to run Reaction on Windows through WSL.

**Comment by nnnnat** [comment]
Thanks @loan-laux for calling this out, we just updated the guide to include info on using it with WSL.
https://mailchimp.com/developer/open-commerce/guides/quick-start/

**Comment by loan-laux** [comment]
That was fast. Thanks @nnnnat!
