### ISSUE TITLE
Improve docs for folks using windows.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/docs#8]
The quick start guide doesn't mention a lot about Windows. It would be nice to have a paragraph explaining the steps for Windows.

This would greatly reduce the number of queries we are getting on Discord related to this.

**Comment by rondlite** [comment]
I am on the case

- [*] Write instructions on how to activate WSL2 in Windows
- [*] Advice a distro and packages to install on Windows Subsystem for Linux needed for Docker
- [ ] Refer to a section in the original docs where the install can continue as already documented

suggestions welcome
